= repols: List GitHub repositories filtered by team

repols is a CLI application that lists GitHub repositories and optionally
repository metadata.


== Installation

Create a GitHub personal access token. The application will prompt you
for the value of your token each time you run it.

The application is available at PyPI. Install it from there using the
following command:

----
pip install repols
----

You can also install directly from the source code by issuing the following
command in the project root:

----
pip install .
----


== Usage

By default, the application simply outputs a list of repository names. The
following command will pipe the list to a file:

----
repols ORGANISATION TEAM > CSV_FILE
----

If the include option is used, the application outputs the fields indicated
by the user instead. The following example, for instance, will display a
list containing the repository names and information on whether the repositories
have been archived.

----
repols  --include name --include archived ORGANISATION TEAM > CSV_FILE
----

Any of the following fields can be included: "archived", "created_at",
"description", "name".
